name: deploy on prod

on :
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps: 
      - uses: actions/checkout@v3
        with:
          node-version: 22
      - run: npm ci 
      - run: npm run build 

      - name: Deploy to server
        env:
          HOST: ${{ secrets.PROD_HOST }}
          USER: ${{ secrets.PROD_USER }}
          KEY: ${{ secrets.PROD_SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "
            git clone https://github.com/TajinderS22/portfolio
            cd portfolio/TajinderSingh &&
            git pull origin main &&
            npm ci &&
            npm run build &&
            sudo cp -r ./dist /var/www/portfolio && 
            sudo nginx -t &&
            sudo nginx -s reload
          "