name: Deploy on Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: Tajinder_Singh       
        run: npm install

      - name: Build React app
        working-directory: Tajinder_Singh
        run: npm run build

      - name: Upload build to server
        env:
          HOST: ${{ secrets.PROD_HOST }}
          USER: ${{ secrets.PROD_USER }}
          KEY: ${{ secrets.PROD_SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem

          # copy the build folder to server
          rsync -avz --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./Tajinder_Singh/dist/ $USER@$HOST:/var/www/portfolio/

          # restart nginx
          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST "sudo nginx -t && sudo systemctl reload nginx"
