name: Deploy on Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get your code from GitHub
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install project dependencies

        run: cd Tajinder_Singh && npm i

      - name: Build your React app
        run: npm run build

      - name: Upload build to your server
        env:
          HOST: ${{ secrets.PROD_HOST }}
          USER: ${{ secrets.PROD_USER }}
          KEY: ${{ secrets.PROD_SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem

          # copy the build folder (dist) to your server
          rsync -avz --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./dist/ $USER@$HOST:/var/www/portfolio/

          # restart nginx so new files are live
          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST "sudo nginx -t && sudo systemctl reload nginx"
