name: Deploy on Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3️⃣ Install dependencies
      - name: Install dependencies
        working-directory: Tajinder_Singh
        run: npm install

      # 4️⃣ Build React app
      - name: Build React app
        working-directory: Tajinder_Singh
        run: npm run build

      # 5️⃣ Upload build to server and reload PM2
      - name: Deploy to server
        env:
          HOST: ${{ secrets.PROD_HOST }}
          USER: ${{ secrets.PROD_USER }}
          KEY: ${{ secrets.PROD_SSH_KEY }}
        run: |
          # Save SSH key
          echo "$KEY" > key.pem
          chmod 600 key.pem

          # Upload build to a temporary folder on server
          rsync -avz --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./Tajinder_Singh/dist/ $USER@$HOST:/tmp/portfolio-temp/

          # Ensure target folder exists and move build there
          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST "
            sudo mkdir -p /home/azureuser/portfolio/Tajinder_Singh
            sudo rsync -avz --delete /tmp/portfolio-temp/ /home/azureuser/portfolio/Tajinder_Singh/dist
            sudo rm -rf /tmp/portfolio-temp/
          "

          # Reload PM2 using full Node/PM2 path in a login shell
          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST "
            bash -l -c 'cd /home/azureuser/portfolio/Tajinder_Singh && /home/azureuser/.nvm/versions/node/v22.20.0/bin/pm2 reload portfolio'
          "
