name: Deploy on Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: Tajinder_Singh
        run: npm install

      - name: Build React app
        working-directory: Tajinder_Singh
        run: npm run build

      - name: Upload build to server
        env:
          HOST: ${{ secrets.PROD_HOST }}
          USER: ${{ secrets.PROD_USER }}
          KEY: ${{ secrets.PROD_SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem

          rsync -avz --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./Tajinder_Singh/dist/ $USER@$HOST:/tmp/portfolio-temp/

          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST "sudo rsync -avz --delete /tmp/portfolio-temp/ /home/ubuntu/portfolio/Tajinder_Singh/dist && sudo rm -rf /tmp/portfolio-temp/"

          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST '
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /home/ubuntu/portfolio/Tajinder_Singh
            pm2 reload portfolio
          '
